Supporting running nested SPM tests (#81)
**Issue**
Fixes #13

**Issue before this change**

When working in a folder where the root folder is not a SPM package, we
were getting the following error:

```
error: Could not find Package.swift in this directory or any of its parent directories.
```

This happened because `swift test` was being ran without a package path,
so SwiftPM tried to resolve `Package.swift` from the workspace root.

**Solution**

Add `--package-path $ZED_DIRNAME` to `swift test`.

`$ZED_DIRNAME` points to the directory of the test file we are
attempting to run. Even when that directory is not the package root,
SwiftPM is able to resolve the owning `Package.swift` by traversing
upwards to the root of the package.

This makes it possible to run tests from nested SPM packages in a folder
or workspace that contains one or many separate SPM packages.

**Testing instructions**

```sh
mkdir testing-this
cd testing-this
swift package init --package-path Nested
zed .
```

If you run the tests before this change then you will see the error
above. With this fix applied, the tests can be ran successfully.

---------

Signed-off-by: Kamaal Farah <kamaal.f1@gmail.com>
Co-authored-by: MrSubidubi <dev@bahn.sh>